"""Export corrected keypoint labels to an Ultralytics YOLO pose dataset.

Takes every frame with a saved label under dataset/labels/ and writes an
images/ + labels/ tree with normalized pose annotations plus a data.yaml,
ready for `yolo pose train`. Re-running regenerates the export from scratch;
the train/val split is deterministic per frame so it stays stable as the
dataset grows.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
from pathlib import Path

from pipeline_manifest import DEFAULT_DATASET_DIR, PROJECT_DIR, load_manifest

DEFAULT_OUT = PROJECT_DIR / "export" / "court_pose"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Export labeled frames as a YOLO pose dataset."
    )
    parser.add_argument(
        "--dataset",
        type=Path,
        default=DEFAULT_DATASET_DIR,
        help=f"Dataset directory (default: {DEFAULT_DATASET_DIR})",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_OUT,
        help=f"Output directory (default: {DEFAULT_OUT})",
    )
    parser.add_argument(
        "--val-frac",
        type=float,
        default=0.2,
        help="Fraction of frames assigned to the val split (default: 0.2)",
    )
    parser.add_argument(
        "--bbox",
        choices=("full", "hull"),
        default="full",
        help="Object bbox: 'full' frame (default) or padded 'hull' of visible points",
    )
    return parser.parse_args()


def split_for(frame_id: str, val_frac: float) -> str:
    digest = int(hashlib.sha1(frame_id.encode("utf-8")).hexdigest(), 16)
    return "val" if (digest % 100) < round(val_frac * 100) else "train"


def bbox_line(keypoints: list[dict], width: int, height: int, mode: str) -> str:
    if mode == "hull":
        xs = [p["x"] for p in keypoints if p["v"] > 0]
        ys = [p["y"] for p in keypoints if p["v"] > 0]
        if xs:
            pad = 0.02
            x_min = max(0.0, min(xs) / width - pad)
            x_max = min(1.0, max(xs) / width + pad)
            y_min = max(0.0, min(ys) / height - pad)
            y_max = min(1.0, max(ys) / height + pad)
            return (
                f"{(x_min + x_max) / 2:.6f} {(y_min + y_max) / 2:.6f} "
                f"{x_max - x_min:.6f} {y_max - y_min:.6f}"
            )
    return "0.500000 0.500000 1.000000 1.000000"


def main() -> None:
    args = parse_args()
    manifest = load_manifest(args.dataset)

    labeled = [
        (frame_id, frame)
        for frame_id, frame in sorted(manifest["frames"].items())
        if frame.get("label_status") == "labeled"
    ]
    if not labeled:
        raise SystemExit("No labeled frames to export. Label some frames first.")

    if args.out.exists():
        shutil.rmtree(args.out)
    for split in ("train", "val"):
        (args.out / "images" / split).mkdir(parents=True, exist_ok=True)
        (args.out / "labels" / split).mkdir(parents=True, exist_ok=True)

    num_keypoints = None
    split_counts = {"train": 0, "val": 0}
    for frame_id, frame in labeled:
        label_file = args.dataset / "labels" / frame["clip_id"] / f"{frame_id}.json"
        if not label_file.is_file():
            print(f"warning: missing label file for {frame_id}, skipping")
            continue
        with open(label_file, "r", encoding="utf-8") as handle:
            label = json.load(handle)

        keypoints = label["keypoints"]
        width, height = label["image_w"], label["image_h"]
        if num_keypoints is None:
            num_keypoints = len(keypoints)
        elif len(keypoints) != num_keypoints:
            raise SystemExit(
                f"{frame_id} has {len(keypoints)} keypoints, expected {num_keypoints}"
            )

        parts = ["0", bbox_line(keypoints, width, height, args.bbox)]
        for point in keypoints:
            if point["v"] == 0:
                parts.append("0.000000 0.000000 0")
            else:
                x = min(1.0, max(0.0, point["x"] / width))
                y = min(1.0, max(0.0, point["y"] / height))
                parts.append(f"{x:.6f} {y:.6f} {point['v']}")

        split = split_for(frame_id, args.val_frac)
        split_counts[split] += 1
        image_src = args.dataset / frame["image"]
        shutil.copy2(image_src, args.out / "images" / split / image_src.name)
        with open(args.out / "labels" / split / f"{frame_id}.txt", "w") as handle:
            handle.write(" ".join(parts) + "\n")

    yaml_text = (
        f"# Generated by export_yolo.py\n"
        f"# NOTE: flip_idx is not defined; train with fliplr: 0.0 until\n"
        f"# left/right keypoint symmetry pairs are specified.\n"
        f"path: {args.out.resolve()}\n"
        f"train: images/train\n"
        f"val: images/val\n"
        f"kpt_shape: [{num_keypoints}, 3]\n"
        f"names:\n  0: court\n"
    )
    with open(args.out / "data.yaml", "w", encoding="utf-8") as handle:
        handle.write(yaml_text)

    print(
        f"Exported {split_counts['train']} train + {split_counts['val']} val "
        f"frames ({num_keypoints} keypoints each) to {args.out}"
    )


if __name__ == "__main__":
    main()
